model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 1024
  image_size: 448
  end_sym: "</s>"
  llama_model: "/home/project/Emotion-LLaMA/checkpoints/Llama-2-7b-chat-hf"

  # ckpt: "/home/czb/big_space/models/minigptv2/minigptv2_checkpoint.pth"
 # ckpt: "/home/project/Emotion-LLaMA/checkpoints/save_checkpoint/MER2023_pseudo_label/20250920/stage2/20250920110/modelFile/checkpoint_29.pth"
# 如果您没有运行 Stage 1 预训练代码，您可以直接设置提供的演示模型参数文件的路径：
# Set Emotion-LLaMA path
  ckpt: "/home/project/Emotion-LLaMA/checkpoints/save_checkpoint/Emoation_LLaMA.pth"
  
  use_grad_checkpoint: True
  chat_template: True
  lora_r: 64
  lora_alpha: 16


datasets:    
  feature_face_caption: 
    batch_size: 1
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 30

run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"

  init_lr: 1e-6
  min_lr: 1e-6
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 30
  num_workers: 6
  iters_per_epoch: 1000


  warmup_steps: 1000

  seed: 42
  output_dir: "/home/project/Emotion-LLaMA/checkpoints/save_checkpoint"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 2
  dist_url: "env://"
  distributed: True

  wandb_log: False
  job_name: minigptv2_finetune
